team_name: "b-it-bots"
robot_pose_topic: "robot_pose"
trajectory_topic: "current_trajectory"
laser_scan_topics: []
laser_scan_frames: []
map_frame: ""
base_frame: "/base_frame"
camera_image_topics: [
  "/rockin/rgb/image"
]
camera_info_topics: [
  "/rockin/rgb/camera_info"
]
camera_frames: [
  "camera_rgb_frame"
]
depth_sensor_topics: [
  "/rockin/depth_0/pointcloud"
]
depth_sensor_frames: [
  "camera_depth_optical_frame"
]
audio_topics: []
robot_to_markerset_transform: [0.575, 0.221, 0.984, 0, 0, 0, 1]
additional_topics: [
  "topic_1",
  "topic_2"
]
